const summarizeBtn = document.getElementById('summarizeBtn');
const openOptionsBtn = document.getElementById('openOptionsBtn');
const statusEl = document.getElementById('status');
const resultEl = document.getElementById('result');
const summaryTypeEl = document.getElementById('summaryType');
const customPromptEl = document.getElementById('customPrompt');
const tierBadgeEl = document.getElementById('tierBadge');
const quotaEl = document.getElementById('quota');
const licenseSection = document.getElementById('licenseSection');
const licenseKeyEl = document.getElementById('licenseKey');
const activateBtn = document.getElementById('activateBtn');
const manageLicenseEl = document.getElementById('manageLicense');
const upgradeEl = document.getElementById('upgradeLink');
const exportBtn = document.getElementById('exportBtn');

function setStatus(message, isError = false) {
  statusEl.textContent = message;
  statusEl.style.color = isError ? '#fca5a5' : '#9ca3af';
}

function setResult(text) {
  resultEl.textContent = text;
  resultEl.classList.remove('hidden');
}

function sendRuntimeMessage(message) {
  return new Promise((resolve) => chrome.runtime.sendMessage(message, resolve));
}

async function getActiveTab() {
  const tabs = await chrome.tabs.query({ active: true, currentWindow: true });
  return tabs[0];
}

function sendMessageToTab(tabId, message) {
  return new Promise((resolve) => chrome.tabs.sendMessage(tabId, message, resolve));
}

function renderState(state) {
  const isPremium = state.tier === 'PREMIUM';
  tierBadgeEl.textContent = isPremium ? 'PREMIUM' : 'FREE';
  tierBadgeEl.className = 'badge ' + (isPremium ? 'badge-premium' : 'badge-free');
  const used = state.usage?.count ?? 0;
  quotaEl.textContent = isPremium ? `Unlimited · ${used} summaries this week` : `${used}/10 summaries used this week`;
  licenseSection.classList.toggle('hidden', isPremium);
  manageLicenseEl.classList.toggle('hidden', !isPremium);
  upgradeEl.classList.toggle('hidden', isPremium);
}

async function refreshState() {
  const res = await sendRuntimeMessage({ type: 'GET_STATE' });
  if (res?.ok) renderState(res);
  return res;
}

async function activateLicense() {
  const key = licenseKeyEl.value.trim();
  if (!key) {
    setStatus('Paste your license key first.', true);
    return;
  }
  setStatus('Validating license...');
  const res = await sendRuntimeMessage({ type: 'ACTIVATE_LICENSE', key });
  if (res?.ok && res.premium) {
    setStatus('Premium activated. Thank you!');
    await refreshState();
  } else if (res?.ok) {
    setStatus('License not valid or not active yet.', true);
  } else {
    setStatus(res?.error || 'Validation failed (network?). Will retry later.', true);
    await refreshState();
  }
}

function toMarkdown(summary) {
  const lines = [`# YouTube Summary`, ``, `_Generated by YouTube Video Summarizer_`, ``];
  return lines.join('\n') + summary;
}

async function copyOrExport() {
  const text = resultEl.textContent;
  if (!text) return;
  const state = await refreshState();
  if (state?.tier === 'PREMIUM') {
    const blob = new Blob([toMarkdown(text)], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'youtube-summary.md';
    a.click();
    URL.revokeObjectURL(url);
    setStatus('Exported as Markdown.');
  } else {
    try {
      await navigator.clipboard.writeText(text);
      setStatus('Copied. (Markdown export is a Premium feature.)');
    } catch (_) {
      setStatus('Copy failed — select the text manually.', true);
    }
  }
}

async function summarizeCurrentVideo() {
  resultEl.classList.add('hidden');
  setStatus('Inspecting current tab...');

  const tab = await getActiveTab();
  if (!tab?.id || !tab.url?.includes('youtube.com/watch')) {
    setStatus('Open a YouTube video page first.', true);
    return;
  }

  setStatus('Extracting transcript...');
  const contextResponse = await sendMessageToTab(tab.id, { type: 'GET_VIDEO_CONTEXT' });
  if (!contextResponse?.ok) {
    setStatus(contextResponse?.error || 'Could not read transcript from the page.', true);
    return;
  }

  setStatus('Generating summary...');
  const summarizeResponse = await sendRuntimeMessage({
    type: 'SUMMARIZE_VIDEO',
    payload: {
      ...contextResponse.payload,
      summaryType: summaryTypeEl.value,
      customPrompt: customPromptEl.value
    }
  });

  if (!summarizeResponse?.ok) {
    if (summarizeResponse?.code === 'UPGRADE') {
      setStatus(summarizeResponse.error, true);
      upgradeEl.classList.add('attention');
    } else {
      setStatus(summarizeResponse?.error || 'Summarization failed.', true);
    }
    return;
  }

  const mode = summarizeResponse.mode === 'longform' ? ` (${summarizeResponse.parts} parts)` : '';
  setStatus(`Done${mode}. Transcript language: ${contextResponse.payload.languageCode}`);
  setResult(summarizeResponse.summary);
}

summarizeBtn.addEventListener('click', () => {
  summarizeCurrentVideo().catch((error) => setStatus(error.message || 'Unexpected error.', true));
});

openOptionsBtn.addEventListener('click', () => chrome.runtime.openOptionsPage());
activateBtn.addEventListener('click', () => activateLicense().catch((e) => setStatus(e.message, true)));
exportBtn.addEventListener('click', () => copyOrExport().catch((e) => setStatus(e.message, true)));
upgradeEl.addEventListener('click', async () => {
  const res = await sendRuntimeMessage({ type: 'GET_PRODUCT_URL' });
  if (res?.url) chrome.tabs.create({ url: res.url });
});

refreshState().catch(() => setStatus('Could not load license state.', true));